### ISSUE TITLE
为什么要用反射来做深copy，而不是普通的取地址 取值 赋值操作呢？

### ISSUE THREAD

**Issue by fxld** [wzshiming/deepclone#1]
https://github.com/wzshiming/deepclone/blob/d7cd858fb95e4649216ada3a499564cbc2671f60/clone.go#L27

**Comment by wzshiming** [comment]
获取类型的内存长度也需要用反射啊, 我认为取地址然后拷贝内存块没有优势, 这样做还非常有可能造成这块拷贝的内存不一定能被 GC 正确的管理.
或者我理解错了?

**Comment by fxld** [comment]
我仔细研究了一下golang反射，用反射深拷贝确实优雅。
感谢回答，我的思维还停留在c。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wzshiming/deepclone"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月15日(星期五) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wzshiming/deepclone] 为什么要用反射来做深copy，而不是普通的取地址 取值 赋值操作呢？ (#1)





 
获取类型的内存长度也需要用反射啊, 我认为取地址然后拷贝内存块没有优势, 这样做还非常有可能造成这块拷贝的内存不一定能被 GC 正确的管理.
 或者我理解错了?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
